#!/bin/bash

if [[ "$1" == "--tr" ]]; then
	kitty &

elif [[ "$1" == "--ff" ]]; then
	firefox &

elif [[ "$1" == "--fm" ]]; then
# kitty -e ranger
thunar &
elif [[ "$1" == "--ob" ]]; then
	obsidian &

elif [[ "$1" == "--dc" ]]; then
	discord &

elif [[ "$1" == "--rd" ]]; then
	firefox --new-tab "https://reddit.com"

elif [[ "$1" == "--wf" ]]; then
 wofi --show run	

fi
